WebSocketConfig:
  # https://docs.docker.com/desktop/networking/#use-cases-and-workarounds-for-all-platforms
  host: host.docker.internal
  port: 8080
  path: /read
  scheme: ws

SocketConfig:
  network: tcp
  # https://medium.com/techanic/docker-containers-ipc-using-sockets-part-1-2ee90885602c
  host: 0.0.0.0
  port: 5555

Buffer: 512